"""empty message

Revision ID: 4c4b18b00837
Revises: e4280ace3546
Create Date: 2023-11-07 18:59:23.822511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4b18b00837'
down_revision = 'e4280ace3546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimo_stock', sa.Integer(), nullable=False))

    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_inventario_minimo', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.drop_column('cantidad_inventario_minimo')

    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.drop_column('minimo_stock')

    # ### end Alembic commands ###
