"""empty message

Revision ID: 8126e8ebda7a
Revises: 
Create Date: 2023-11-16 16:25:11.110447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8126e8ebda7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_primas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('clasificacion', sa.String(length=80), nullable=False),
    sa.Column('unidad_medida', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('rinde', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingredientes_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materias_primas_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_necesaria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materias_primas_id'], ['materias_primas.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_materias_primas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('materias_primas_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_stock', sa.Integer(), nullable=False),
    sa.Column('minimo_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materias_primas_id'], ['materias_primas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_producto_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_inventario', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(length=80), nullable=False),
    sa.Column('cantidad_inventario_minimo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_receta')
    op.drop_table('user_producto_final')
    op.drop_table('user_materias_primas')
    op.drop_table('ingredientes_receta')
    op.drop_table('user')
    op.drop_table('receta')
    op.drop_table('materias_primas')
    # ### end Alembic commands ###
