"""empty message

Revision ID: c50d9902e66b
Revises: 0683d1d7aee3
Create Date: 2023-11-27 17:44:38.107166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50d9902e66b'
down_revision = '0683d1d7aee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
